FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY classificationui.py classificationui.py
COPY logistic_model.pkl logistic_model.pkl

EXPOSE 8501

CMD ["streamlit", "run", "classificationui.py", "--server.port=8501", "--server.address=0.0.0.0"]