FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py app.py
COPY logistic_model.pkl logistic_model.pkl

EXPOSE 5000

CMD ["python", "app.py"]