version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask-api